import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Sparkles, Send, Bot, User } from "lucide-react";

const SUGGESTIONS = [
  "Summarize today's pending cases",
  "Draft follow-up messages for overdue cases",
  "List overdue tasks by agent",
  "Generate a daily ops report",
  "Identify operational bottlenecks this week",
];

type Msg = { role: "user" | "assistant"; text: string };

export const Route = createFileRoute("/assistant")({
  head: () => ({ meta: [{ title: "AI Assistant — Agency Ops" }] }),
  component: AssistantPage,
});

function AssistantPage() {
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Msg[]>([
    { role: "assistant", text: "Hi — I'm your Agency Ops assistant. AI is not wired up yet, but the surface is ready. Try a suggestion below." },
  ]);

  const send = (text: string) => {
    if (!text.trim()) return;
    setMessages((m) => [...m, { role: "user", text },
      { role: "assistant", text: "AI integration coming soon. This response will be generated by a LangGraph agent with access to cases, tasks, claims, recruitment, and reports." },
    ]);
    setInput("");
  };

  return (
    <div>
      <PageHeader
        title="AI Assistant"
        description="Placeholder surface — LangGraph agent will plug in here."
      />
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2 flex flex-col h-[600px]">
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary" />Conversation</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-1 flex-col gap-3 overflow-y-auto">
            {messages.map((m, i) => (
              <div key={i} className={`flex gap-2 ${m.role === "user" ? "justify-end" : ""}`}>
                {m.role === "assistant" && (
                  <div className="h-7 w-7 shrink-0 rounded-full bg-primary/10 text-primary flex items-center justify-center">
                    <Bot className="h-4 w-4" />
                  </div>
                )}
                <div className={`max-w-[80%] rounded-lg px-3 py-2 text-sm ${
                  m.role === "user" ? "bg-primary text-primary-foreground" : "bg-muted text-foreground"
                }`}>
                  {m.text}
                </div>
                {m.role === "user" && (
                  <div className="h-7 w-7 shrink-0 rounded-full bg-secondary text-secondary-foreground flex items-center justify-center">
                    <User className="h-4 w-4" />
                  </div>
                )}
              </div>
            ))}
          </CardContent>
          <div className="border-t border-border p-3">
            <div className="flex gap-2">
              <Textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask anything about your agency operations…"
                className="min-h-[44px] resize-none"
                onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(input); } }}
              />
              <Button onClick={() => send(input)} size="icon"><Send className="h-4 w-4" /></Button>
            </div>
          </div>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Suggestions</CardTitle>
            <CardDescription>Quick prompts to try</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {SUGGESTIONS.map((s) => (
              <button key={s} onClick={() => send(s)}
                className="block w-full rounded-md border border-border bg-background px-3 py-2 text-left text-sm hover:bg-accent/40">
                {s}
              </button>
            ))}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}